
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beoslctdbyawjvxuthjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlb3NsY3RkYnlhd2p2eHV0aGp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDk0MjgsImV4cCI6MjA1OTkyNTQyOH0.drC8ni317Azvpcv9ZYCx6HRx9NPIsdiv5CFpk1YEs-c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    }
  }
);
